//! Typed events for the Geth-compatible log value stream.

use crate::{address_value, topic_value, Params, ParamsError};
use alloy_primitives::{Address, B256};
use std::collections::VecDeque;

/// Version of the rules that assign absolute log value indices.
///
/// This is deliberately separate from [`Params`]. Parameters describe numerical filter-map
/// dimensions; a value-space version describes semantic rules such as entry ordering and block
/// delimiter placement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ValueSpaceVersion {
    /// Geth's first value-space layout: address before topics and one trailing, unmarked block
    /// delimiter.
    GethV1 = 1,
}

/// Geth's first value-space layout.
pub const GETH_V1: ValueSpaceVersion = ValueSpaceVersion::GethV1;

impl From<ValueSpaceVersion> for u8 {
    fn from(version: ValueSpaceVersion) -> Self {
        version as Self
    }
}

impl TryFrom<u8> for ValueSpaceVersion {
    type Error = UnknownValueSpaceVersion;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::GethV1),
            value => Err(UnknownValueSpaceVersion(value)),
        }
    }
}

/// Error returned when decoding an unsupported persisted value-space version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("unknown value-space version {0}")]
pub struct UnknownValueSpaceVersion(u8);

impl UnknownValueSpaceVersion {
    /// Creates an unknown-version error for the rejected encoded value.
    pub const fn new(value: u8) -> Self {
        Self(value)
    }

    /// Returns the rejected encoded value.
    pub const fn value(self) -> u8 {
        self.0
    }
}

/// A point from which a log value stream can be reproduced.
///
/// The numerical pointer is the first non-padding slot generated by the block: its first log's
/// address when it has logs, or its delimiter when it is empty. Map-boundary padding emitted before
/// that slot belongs to the preceding block's range.
///
/// The stream verifies that the first input's block identity matches this value, but trusts the
/// supplied numerical pointer. Establishing checkpoint provenance and canonical-chain membership
/// belongs to the origin or checkpoint layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ValueSpaceAnchor {
    /// Number of the anchored block.
    pub block_number: u64,
    /// Hash of the anchored block.
    pub block_hash: B256,
    /// Absolute index of the first non-padding slot generated by the anchored block.
    pub first_log_value_index: u64,
}

impl ValueSpaceAnchor {
    /// Creates an anchor binding a block identity to its first absolute log value index.
    pub const fn new(block_number: u64, block_hash: B256, first_log_value_index: u64) -> Self {
        Self { block_number, block_hash, first_log_value_index }
    }
}

/// One input block and its logs in canonical receipt order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlockInput {
    /// Block number.
    pub number: u64,
    /// Block hash.
    pub hash: B256,
    /// Logs flattened in receipt order and then in-log order.
    pub logs: Vec<LogInput>,
}

impl BlockInput {
    /// Creates a block input.
    pub fn new(number: u64, hash: B256, logs: impl IntoIterator<Item = LogInput>) -> Self {
        Self { number, hash, logs: logs.into_iter().collect() }
    }
}

/// Searchable content contributed by one Ethereum log.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LogInput {
    /// Emitting address.
    pub address: Address,
    /// Topics in their declared order.
    pub topics: Vec<B256>,
}

impl LogInput {
    /// Creates a log input.
    pub fn new(address: Address, topics: impl IntoIterator<Item = B256>) -> Self {
        Self { address, topics: topics.into_iter().collect() }
    }
}

/// Metadata mapping a block to its first non-padding slot in the value space.
///
/// This points to the first log address when the block has logs, or the block delimiter when it is
/// empty. Any map-boundary padding before it belongs to the preceding block's range. A block
/// pointer is metadata: it does not consume a log value index and is not a filter-map slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlockPointer {
    /// Block number.
    pub block_number: u64,
    /// Block hash.
    pub block_hash: B256,
    /// Absolute index of the first non-padding slot generated by this block.
    pub first_log_value_index: u64,
}

impl BlockPointer {
    /// Creates a block pointer.
    pub const fn new(block_number: u64, block_hash: B256, first_log_value_index: u64) -> Self {
        Self { block_number, block_hash, first_log_value_index }
    }
}

/// An entry that consumes one absolute log value index.
///
/// Searchable values, delimiters, and padding are slots. This differs from metadata events such as
/// [`BlockPointer`], which describe positions without occupying one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogValueSlot {
    /// A searchable address or topic hash.
    Value {
        /// Absolute log value index occupied by this slot.
        index: u64,
        /// SHA-256 hash of the address or topic.
        value: B256,
    },
    /// An unmarked entry closing a block that is no longer the current head.
    BlockDelimiter {
        /// Absolute log value index occupied by this slot.
        index: u64,
        /// Number of the block closed by this delimiter.
        block_number: u64,
        /// Hash of the block closed by this delimiter.
        block_hash: B256,
    },
    /// An unmarked entry consumed so one log does not cross a map boundary.
    Padding {
        /// Absolute log value index occupied by this slot.
        index: u64,
    },
}

/// An observable event produced while materializing the value space.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogValueStreamEvent {
    /// Block-to-index metadata; does not consume a slot.
    BlockPointer(BlockPointer),
    /// A materialized slot in the value space.
    Slot(LogValueSlot),
}

/// The current head's delimiter, reserved at an absolute index but not materialized yet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PendingDelimiter {
    /// Current head block number.
    pub block_number: u64,
    /// Current head block hash.
    pub block_hash: B256,
    /// Absolute index reserved for the delimiter.
    pub index: u64,
}

impl PendingDelimiter {
    /// Creates pending-delimiter metadata.
    pub const fn new(block_number: u64, block_hash: B256, index: u64) -> Self {
        Self { block_number, block_hash, index }
    }
}

/// Explicit meaning of the end of the supplied input.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogValueStreamTermination {
    /// The final input block is the canonical head, so its delimiter remains pending.
    ReachedHead,
    /// The final input block only ends this bounded batch, so its delimiter is materialized.
    BatchExhausted,
}

/// State needed to continue after a bounded batch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BatchContinuation {
    /// Number expected for the first block in the next batch.
    pub next_block_number: u64,
    /// Absolute cursor immediately after the last batch block's materialized delimiter.
    pub next_log_value_index: u64,
}

impl BatchContinuation {
    /// Creates bounded-batch continuation state.
    pub const fn new(next_block_number: u64, next_log_value_index: u64) -> Self {
        Self { next_block_number, next_log_value_index }
    }
}

/// Successful terminal state of a log value stream.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogValueStreamCompletion {
    /// The canonical head was reached, leaving its delimiter pending.
    ReachedHead {
        /// Pointer of the current head block.
        head: BlockPointer,
        /// Current head's delimiter, which becomes a slot only when a child block arrives.
        pending_delimiter: PendingDelimiter,
    },
    /// A bounded input batch ended before the canonical head.
    BatchExhausted {
        /// Pointer of the final block in the batch.
        last_block: BlockPointer,
        /// Cursor from which the next batch can continue.
        continuation: BatchContinuation,
    },
}

/// A yielded stream item.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogValueStreamItem {
    /// A non-terminal event.
    Event(LogValueStreamEvent),
    /// The terminal state. Once yielded, the iterator is fused.
    Complete(LogValueStreamCompletion),
}

/// Failure produced while validating or advancing a log value stream.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum LogValueStreamError {
    /// No block was supplied for the anchor.
    #[error("the value-space stream has no input block")]
    EmptyInput,
    /// The numerical parameter set is invalid.
    #[error("invalid filter-map parameters: {0}")]
    InvalidParams(#[from] ParamsError),
    /// The first input block does not have the anchor's number.
    #[error("anchor block number mismatch: expected {expected}, got {actual}")]
    AnchorBlockNumberMismatch {
        /// Number bound by the anchor.
        expected: u64,
        /// Number of the first input block.
        actual: u64,
    },
    /// The first input block does not have the anchor's hash.
    #[error("anchor block hash mismatch: expected {expected}, got {actual}")]
    AnchorBlockHashMismatch {
        /// Hash bound by the anchor.
        expected: B256,
        /// Hash of the first input block.
        actual: B256,
    },
    /// Input blocks are not contiguous.
    #[error("non-contiguous input block: expected {expected}, got {actual}")]
    NonContiguousBlock {
        /// Number required by the preceding block.
        expected: u64,
        /// Number of the next input block.
        actual: u64,
    },
    /// The anchor points before padding required by its first log.
    #[error("anchor index {index} requires {padding} padding slots before its first log")]
    AnchorRequiresPadding {
        /// Anchored absolute log value index.
        index: u64,
        /// Number of padding slots required before the first log.
        padding: u64,
    },
    /// Advancing the absolute index would overflow `u64`.
    #[error("log value index overflow")]
    LogValueIndexOverflow,
    /// Deriving the next expected block number would overflow `u64`.
    #[error("block number overflow")]
    BlockNumberOverflow,
}

/// Iterator that turns canonical blocks into typed value-space events.
#[derive(Debug, Clone)]
pub struct LogValueStream {
    params: Params,
    anchor: ValueSpaceAnchor,
    blocks: VecDeque<BlockInput>,
    termination: LogValueStreamTermination,
    queued: VecDeque<LogValueStreamItem>,
    next_index: u64,
    next_block_number: u64,
    initialized: bool,
    fused: bool,
}

impl LogValueStream {
    /// Value-space rules implemented by this stream.
    pub const VALUE_SPACE_VERSION: ValueSpaceVersion = GETH_V1;

    /// Creates a stream at `anchor` over canonical `blocks` with an explicit input termination.
    pub fn new(
        params: Params,
        anchor: ValueSpaceAnchor,
        blocks: impl IntoIterator<Item = BlockInput>,
        termination: LogValueStreamTermination,
    ) -> Self {
        Self {
            params,
            anchor,
            blocks: blocks.into_iter().collect(),
            termination,
            queued: VecDeque::new(),
            next_index: anchor.first_log_value_index,
            next_block_number: anchor.block_number,
            initialized: false,
            fused: false,
        }
    }

    fn prepare_block(&mut self) -> Result<(), LogValueStreamError> {
        if !self.initialized {
            self.params.validate()?;
        }

        let block = self.blocks.pop_front().ok_or(LogValueStreamError::EmptyInput)?;
        if !self.initialized {
            if block.number != self.anchor.block_number {
                return Err(LogValueStreamError::AnchorBlockNumberMismatch {
                    expected: self.anchor.block_number,
                    actual: block.number,
                })
            }
            if block.hash != self.anchor.block_hash {
                return Err(LogValueStreamError::AnchorBlockHashMismatch {
                    expected: self.anchor.block_hash,
                    actual: block.hash,
                })
            }
        } else if block.number != self.next_block_number {
            return Err(LogValueStreamError::NonContiguousBlock {
                expected: self.next_block_number,
                actual: block.number,
            })
        }

        if let Some(first_log) = block.logs.first() {
            let padding = self.padding_before(first_log);
            if !self.initialized && padding != 0 {
                return Err(LogValueStreamError::AnchorRequiresPadding {
                    index: self.next_index,
                    padding,
                })
            }
            self.queue_padding(padding)?;
        }

        let pointer = BlockPointer::new(block.number, block.hash, self.next_index);
        self.queued
            .push_back(LogValueStreamItem::Event(LogValueStreamEvent::BlockPointer(pointer)));

        for (log_index, log) in block.logs.iter().enumerate() {
            if log_index != 0 {
                let padding = self.padding_before(log);
                self.queue_padding(padding)?;
            }
            self.queue_value(address_value(log.address))?;
            for &topic in &log.topics {
                self.queue_value(topic_value(topic))?;
            }
        }

        self.initialized = true;
        let input_ended = self.blocks.is_empty();
        if input_ended && self.termination == LogValueStreamTermination::ReachedHead {
            let pending_delimiter =
                PendingDelimiter::new(block.number, block.hash, self.next_index);
            self.queued.push_back(LogValueStreamItem::Complete(
                LogValueStreamCompletion::ReachedHead { head: pointer, pending_delimiter },
            ));
            return Ok(())
        }

        let index = self.next_index;
        self.queued.push_back(LogValueStreamItem::Event(LogValueStreamEvent::Slot(
            LogValueSlot::BlockDelimiter {
                index,
                block_number: block.number,
                block_hash: block.hash,
            },
        )));
        self.advance_index()?;
        self.next_block_number =
            block.number.checked_add(1).ok_or(LogValueStreamError::BlockNumberOverflow)?;

        if input_ended {
            let continuation = BatchContinuation::new(self.next_block_number, self.next_index);
            self.queued.push_back(LogValueStreamItem::Complete(
                LogValueStreamCompletion::BatchExhausted { last_block: pointer, continuation },
            ));
        }
        Ok(())
    }

    const fn padding_before(&self, log: &LogInput) -> u64 {
        let entry_count = 1 + log.topics.len() as u64;
        let values_per_map = self.params.values_per_map();
        let remaining = values_per_map - self.next_index % values_per_map;
        if entry_count > remaining {
            remaining
        } else {
            0
        }
    }

    fn queue_padding(&mut self, count: u64) -> Result<(), LogValueStreamError> {
        for _ in 0..count {
            let index = self.next_index;
            self.queued.push_back(LogValueStreamItem::Event(LogValueStreamEvent::Slot(
                LogValueSlot::Padding { index },
            )));
            self.advance_index()?;
        }
        Ok(())
    }

    fn queue_value(&mut self, value: B256) -> Result<(), LogValueStreamError> {
        let index = self.next_index;
        self.queued.push_back(LogValueStreamItem::Event(LogValueStreamEvent::Slot(
            LogValueSlot::Value { index, value },
        )));
        self.advance_index()
    }

    fn advance_index(&mut self) -> Result<(), LogValueStreamError> {
        self.next_index =
            self.next_index.checked_add(1).ok_or(LogValueStreamError::LogValueIndexOverflow)?;
        Ok(())
    }
}

impl Iterator for LogValueStream {
    type Item = Result<LogValueStreamItem, LogValueStreamError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.fused {
            return None
        }
        if self.queued.is_empty() &&
            let Err(error) = self.prepare_block()
        {
            self.fused = true;
            self.queued.clear();
            return Some(Err(error))
        }
        let item = self.queued.pop_front()?;
        if matches!(item, LogValueStreamItem::Complete(_)) {
            self.fused = true;
            self.queued.clear();
        }
        Some(Ok(item))
    }
}

impl std::iter::FusedIterator for LogValueStream {}
