[package]
name = "reth-filter-maps"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "FilterMaps local search index for log queries"

[lints]
workspace = true

[dependencies]
# ethereum
alloy-primitives.workspace = true

# crypto
sha2.workspace = true

# misc
schnellru.workspace = true
thiserror.workspace = true

[dev-dependencies]
reth-filter-maps-test-utils.workspace = true
