[package]
name = "reth-filter-maps"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "FilterMaps local search index for log queries"

[lints]
workspace = true

[dependencies]
# reth
reth-chain-state.workspace = true
reth-metrics.workspace = true
reth-prune-types.workspace = true
reth-storage-api = { workspace = true, features = ["std"] }
reth-storage-errors.workspace = true

# ethereum
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true

# crypto
sha2.workspace = true

# storage
rocksdb.workspace = true

# async
tokio = { workspace = true, features = ["sync", "macros"] }

# misc
metrics.workspace = true
schnellru.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
reth-ethereum-primitives.workspace = true
reth-filter-maps-test-utils.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
proptest.workspace = true
tempfile.workspace = true
