//! Pinned Geth `FORMAT 2` pipeline fixtures.
//!
//! The corpus is generated by the fork-only pipeline oracle named in every fixture header, driven
//! by the pinned go-ethereum revision. `manifest` pins the file set, digests, and content counts;
//! `parser` accepts only the canonical text form and checks the relationships between sections;
//! `replay` drives every fixture through the pure log value stream and checks only recorded
//! pointer, boundary, termination, and slot-classification evidence against emitted events.

#[path = "golden_pipeline/manifest.rs"]
pub(crate) mod manifest;
#[path = "golden_pipeline/parser.rs"]
pub(crate) mod parser;
#[path = "golden_pipeline/replay.rs"]
mod replay;

use parser::{BoundaryEnding, FixtureClass, Origin, ParamsName, Planner, TopicConstraint};

#[test]
fn manifested_pipeline_corpus_is_valid() {
    let corpus = manifest::load_and_validate_corpus().unwrap();
    assert!(!corpus.is_empty(), "the manifest lists no fixtures");
}

#[test]
fn every_fixture_replays_through_the_log_value_stream() {
    for (entry, fixture) in &manifest::load_and_validate_corpus().unwrap() {
        replay::check(&entry.path, fixture).unwrap();
    }
}

/// The replay checks only prove what the corpus exercises, so pin the shapes it must contain.
#[test]
fn corpus_exercises_every_shape_the_replay_distinguishes() {
    let corpus = manifest::load_and_validate_corpus().unwrap();
    let fixtures = corpus.iter().map(|(_, fixture)| fixture).collect::<Vec<_>>();
    let curated = [
        "empty-and-shared-map",
        "topic-cardinality",
        "boundary-by-value",
        "boundary-by-delimiter",
        "boundary-by-padding",
        "default-overflow",
        "epoch-boundary",
        "head-and-bounded-continuation",
        "matcher-address-and-topics",
        "matcher-alternatives-and-wildcards",
        "matcher-no-match-and-dedup",
        "matcher-false-positives",
        "positional-isolation",
        "default-end-to-end",
    ];
    for scenario in curated {
        assert!(fixtures.iter().any(|fixture| fixture.scenario == scenario), "missing {scenario}");
    }
    assert_eq!(
        fixtures.iter().filter(|fixture| fixture.class == FixtureClass::Stress).count(),
        16,
        "the pinned stress corpus must contain exactly sixteen scenarios"
    );
    assert_eq!(fixtures.len(), 30, "the corpus must contain 14 curated and 16 stress fixtures");
    assert!(
        corpus.iter().map(|(entry, _)| entry.bytes).sum::<usize>() < 1024 * 1024,
        "the corpus exceeds its approximate 1 MiB budget"
    );
    for class in [FixtureClass::Focused, FixtureClass::EndToEnd, FixtureClass::Stress] {
        assert!(fixtures.iter().any(|f| f.class == class), "no {class:?} fixture");
    }
    for params in [ParamsName::Default, ParamsName::Range] {
        assert!(fixtures.iter().any(|f| f.params_name == params), "no {params:?} fixture");
    }
    assert!(fixtures.iter().any(|f| matches!(f.origin, Origin::Continuation { .. })));
    assert!(fixtures.iter().any(|f| matches!(f.origin, Origin::Checkpoint(_))));
    for ending in [BoundaryEnding::Value, BoundaryEnding::Delimiter, BoundaryEnding::Padding] {
        let present = fixtures.iter().any(|f| f.boundaries.iter().any(|b| b.ending == ending));
        assert!(present, "no map completed by a {ending:?} slot");
    }
    assert!(fixtures.iter().any(|f| f.completed_maps.len() > 1), "no multi-map fixture");
    assert!(fixtures.iter().any(|f| f.partial_maps.is_empty()), "no fixture ending on a map");
    assert!(fixtures.iter().any(|f| f.completed_maps.iter().any(|m| m.pointer_blocks.is_empty())));
    assert!(fixtures.iter().any(|f| f.blocks.iter().any(|b| b.receipts.is_empty())));
    let widest = fixtures
        .iter()
        .flat_map(|f| &f.completed_maps)
        .flat_map(|m| &m.rows)
        .map(|r| r.columns.len())
        .max();
    assert!(widest > Some(8), "no row overflows the base mapping layer");

    let queries = fixtures.iter().flat_map(|f| &f.queries).collect::<Vec<_>>();
    assert!(queries.iter().any(|q| q.planner == Planner::EveryBlock), "no ErrMatchAll query");
    let no_match = queries.iter().any(|q| q.planner == Planner::Matcher && q.exact_logs.is_empty());
    assert!(no_match, "no matcher query without matches");
    let false_positive = queries.iter().any(|q| q.potential_logs.len() > q.exact_logs.len());
    assert!(false_positive, "no false positive");
    assert!(queries.iter().any(|q| q.addresses.len() > 1), "no address alternatives");
    assert!(queries.iter().any(|q| q.topics.len() == 4), "no four-topic query");
    let wildcard = queries.iter().any(|q| q.topics.contains(&TopicConstraint::Any));
    assert!(wildcard, "no wildcard topic position");
}
